#!/bin/bash
# Setup cuDNN / CTranslate2: persist LD_LIBRARY_PATH + ตรวจสอบ GPU support
#
# ใช้ไฟล์เดียวสำหรับทุกอย่าง:
#   - ตั้งค่าและ persist LD_LIBRARY_PATH (start-pod/start-rq-workers โหลดอัตโนมัติ)
#   - ตรวจสอบ cuDNN libraries และทดสอบ ctranslate2/faster-whisper
#
# วิธีใช้ (หลัง apt install ffmpeg, pip install -r requirements.txt):
#   ./scripts/utility/setup-cudnn-env.sh
# จากนั้นรัน start-pod.sh และ start-rq-workers.sh ได้เลย
#
# ถ้า container มีสิทธิ root: จะเขียนลง /etc/profile.d และ /etc/ld.so.conf.d ด้วย

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Paths (order: cuDNN → system → CUDA → CTranslate2)
# CUDA: ลองตามลำดับ (RunPod 12.8 ใช้ cuda-12.8, container เก่าใช้ cuda-12.1)
CUDNN_LIB_PATH="/usr/local/lib/python3.10/dist-packages/nvidia/cudnn/lib"
CUDNN_LIB_PATH_311="/usr/local/lib/python3.11/site-packages/nvidia/cudnn/lib"
SYSTEM_PATH="/usr/lib/x86_64-linux-gnu"
CUDA_LIB_PATH="/usr/local/cuda-12.8/lib64"
CUDA_LIB_PATH_121="/usr/local/cuda-12.1/lib64"
CUDA_LIB_PATH_LINK="/usr/local/cuda/lib64"
CTRANSLATE2_LIB_PATH="/usr/local/lib/python3.10/dist-packages/ctranslate2.libs"
CTRANSLATE2_LIB_PATH_311="/usr/local/lib/python3.11/site-packages/ctranslate2.libs"

echo "🔧 Setup cuDNN / CTranslate2 environment"
echo ""

# 1. สร้าง LD_LIBRARY_PATH (รวม paths ที่มีอยู่จริง)
NEW_LD_PATH=""
for path in "$CUDNN_LIB_PATH" "$CUDNN_LIB_PATH_311" "$SYSTEM_PATH" "$CUDA_LIB_PATH" "$CUDA_LIB_PATH_121" "$CUDA_LIB_PATH_LINK" "$CTRANSLATE2_LIB_PATH" "$CTRANSLATE2_LIB_PATH_311"; do
    if [ -d "$path" ]; then
        if echo ":$NEW_LD_PATH:" | grep -q ":$path:"; then
            : # already in path
        else
            [ -n "$NEW_LD_PATH" ] && NEW_LD_PATH="$NEW_LD_PATH:$path" || NEW_LD_PATH="$path"
            echo "  ✅ $path"
        fi
    fi
done

if [ -z "$NEW_LD_PATH" ]; then
    echo "❌ No library paths found. Check cuDNN/CUDA/ctranslate2 install."
    exit 1
fi
echo ""

# 2. Persist: เขียนลงไฟล์ในโปรเจกต์ (start-pod/start-rq-workers โหลดอัตโนมัติ)
LD_PATH_FILE="$PROJECT_ROOT/scripts/utility/.cudnn-ldpath.sh"
mkdir -p "$(dirname "$LD_PATH_FILE")"
cat > "$LD_PATH_FILE" << EOF
# Auto-generated by setup-cudnn-env.sh - do not edit
export LD_LIBRARY_PATH="$NEW_LD_PATH:\${LD_LIBRARY_PATH:-}"
EOF
echo "✅ Wrote $LD_PATH_FILE"
export LD_LIBRARY_PATH="$NEW_LD_PATH:${LD_LIBRARY_PATH:-}"

# 3. ถ้ามีสิทธิ root: เขียนลง /etc
if [ -w /etc/profile.d ] 2>/dev/null; then
    cat > /etc/profile.d/cudnn-ctranslate2.sh << EOF
# CTranslate2/cuDNN - generated by setup-cudnn-env.sh
export LD_LIBRARY_PATH="$NEW_LD_PATH:\${LD_LIBRARY_PATH:-}"
EOF
    echo "✅ Wrote /etc/profile.d/cudnn-ctranslate2.sh"
fi
if [ -w /etc/ld.so.conf.d ] 2>/dev/null; then
    LDCONF="/etc/ld.so.conf.d/cudnn-ctranslate2.conf"
    : > "$LDCONF"
    for path in "$CUDNN_LIB_PATH" "$CUDNN_LIB_PATH_311" "$SYSTEM_PATH" "$CUDA_LIB_PATH" "$CUDA_LIB_PATH_121" "$CUDA_LIB_PATH_LINK" "$CTRANSLATE2_LIB_PATH" "$CTRANSLATE2_LIB_PATH_311"; do
        [ -d "$path" ] && echo "$path" >> "$LDCONF"
    done
    [ -s "$LDCONF" ] && ldconfig 2>/dev/null || true
    echo "✅ Updated $LDCONF and ran ldconfig"
fi
ldconfig 2>/dev/null || true
echo ""

# 4. ตรวจสอบ cuDNN libraries (รองรับ cuDNN 8 และ 9)
echo "4️⃣ Checking cuDNN libraries..."
for file in libcudnn.so.9 libcudnn_ops_infer.so.9 libcudnn.so.8 libcudnn_ops_infer.so.8 libcudnn_cnn_infer.so.8; do
    found=false
    for path in "$CUDNN_LIB_PATH" "$CUDNN_LIB_PATH_311" "$SYSTEM_PATH" "$CUDA_LIB_PATH" "$CUDA_LIB_PATH_121" "$CUDA_LIB_PATH_LINK"; do
        [ -d "$path" ] && [ -f "$path/$file" ] && { echo "  ✅ Found: $path/$file"; found=true; break; }
    done
    [ "$found" = false ] && echo "  ⚠️  Not found: $file"
done
echo ""

# 5. ทดสอบ ctranslate2 + faster-whisper (รับ LD_LIBRARY_PATH จาก env ที่ export ไว้แล้ว)
echo "5️⃣ Testing ctranslate2 / faster-whisper CUDA..."
# ปิด HF_HUB_ENABLE_HF_TRANSFER ชั่วคราว (ถ้าไม่มี pip install hf_transfer)
# เพื่อหลีกเลี่ยง: ValueError: Fast download using 'hf_transfer' is enabled but 'hf_transfer' package is not available
unset HF_HUB_ENABLE_HF_TRANSFER 2>/dev/null || true
export HF_HUB_ENABLE_HF_TRANSFER=0

python3 << 'PYTHON'
import os
import sys

# รับจาก env ที่ parent set ไว้
ld_path = os.environ.get("LD_LIBRARY_PATH", "")
if not ld_path:
    print("  ⚠️  LD_LIBRARY_PATH not set in this process")
    sys.exit(1)

try:
    import ctranslate2
    print(f"  ✅ ctranslate2 version: {ctranslate2.__version__}")
    cuda_types = ctranslate2.get_supported_compute_types("cuda")
    if cuda_types:
        print(f"  ✅ CUDA support: {', '.join(sorted(cuda_types))}")
    else:
        print("  ❌ CUDA support: NOT available")
        sys.exit(1)
    from faster_whisper import WhisperModel
    print("  🧪 Loading WhisperModel (tiny, float16)...")
    model = WhisperModel("tiny", device="cuda", compute_type="float16")
    print("  ✅ Model created successfully!")
except ImportError as e:
    print(f"  ❌ Import error: {e}")
    sys.exit(1)
except Exception as e:
    print(f"  ❌ Error: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)
PYTHON

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ cuDNN/CTranslate2 setup complete"
    echo "   start-pod.sh / start-rq-workers.sh จะโหลด LD_LIBRARY_PATH จาก $LD_PATH_FILE อัตโนมัติ"
    echo ""
    echo "📋 Next: ./scripts/pod/start-pod.sh แล้ว ./scripts/pod/start-rq-workers.sh"
else
    echo ""
    echo "❌ Verification failed. Try: pip3 install ctranslate2==4.4.0 faster-whisper --no-cache-dir"
    exit 1
fi
